feat: add types for nmr spectra
cheminfo/cheminfo-types pull request #45
Opened 2021-05-21 19:15 UTC by jobo322

2021-05-25 06:47 UTC, kjappelbaum commented
Thanks, I'd like to discuss with @lpatiny about the plan for these types and then merge

2021-06-18 11:43 UTC, jobo322 commented
@kjappelbaum I did rebase this branch with your recent changes, 

do you are able to use this library via npm link?

2021-06-21 13:14 UTC, lpatiny requested changes

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Integral.ts
> +  integral: number;
Should be renamed to integration I think (and maybe also in nmrium and nmr-load-save)

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Jcoupling.ts
> +export interface Jcoupling {
I would also have C uppercase: `JCoupling`

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Peaks/Peak1D.ts
> +  mu?: number;
Are we using somewhere this `mu` ? it seems not general enough so better remove it if we don't use it.

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Peaks/Peak1D.ts
> +  originX?: number;
We should only keep `x` and `y` that contains originX and originY. Also to check with Hamed to change NMRium.

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Peaks/Peak1D.ts
> +  x: number;
@kjappelbaum Should we keep `x` and `y` property names or rather use `delta` and `intensity` as names.

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Peaks/Peak2D.ts
> +  originX?: number;
Same comment here about `originX` / `x`

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Ranges/Range.ts
> +  integral: number;
Should be `integration` and not `integral`

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Signals/Signal2D.ts
> +  sign?: number;
What is this `sign` ?

2021-06-21 13:14 UTC, lpatiny commented on src/spectra/nmr/Spectra/Spectrum1D.ts
> +  originalInfo: any;
Strange that we need duplicate here as well.

2021-06-21 13:23 UTC, hamed-musallam commented on src/spectra/nmr/spectrum/Data1D.d.ts
> +  y: Array<number>;
@lpatiny 
we use y when we switch between real/imaginary part.

2021-06-21 13:26 UTC, hamed-musallam commented on src/spectra/nmr/Peaks/Peak1D.ts
> +  originX?: number;
@lpatiny 
yes that is true for export only but for internal use in numrium we still need both the original and current value because of shift

2021-06-21 13:27 UTC, hamed-musallam commented on src/spectra/nmr/Peaks/Peak1D.ts
> +  x: number;
@lpatiny 
if we are going yo change it here we need also to change it in numrium.

2021-06-21 13:28 UTC, hamed-musallam commented on src/spectra/nmr/Peaks/Peak2D.ts
> +  originX?: number;
https://github.com/cheminfo/cheminfo-types/pull/45#discussion_r655374110

we still need it for internal use in numrium

2021-06-21 13:30 UTC, hamed-musallam commented on src/spectra/nmr/Spectra/Spectrum1D.ts
> +  originalInfo: any;
@lpatiny 
we need both orignal info and data to reapply the filters.

2021-06-22 06:15 UTC, targos commented on src/spectra/nmr/Peaks/Peak1D.ts
> +  originX?: number;
we should not have types specific to internals of nmrium in this package

2021-06-22 06:30 UTC, hamed-musallam commented on src/spectra/nmr/Peaks/Peak1D.ts
> +  originX?: number;
@targos 
yes i agree with you this why I said we must look for what we export in the JSON file (.numrium) and base on it make the types

2021-09-26 06:10 UTC, closed without merging